theme: jekyll-theme-slate

/* Unordered list <ul> symbols:
 * - level 2 is hollow circle
 * - level 3 is filled square
 * - ul default is filled disc (bullet)
 */
ul ul {
        list-style-type:  circle;
}

ul ul ul {
        list-style-type:  square;
}
